onjoin-tools: true
navigator:
  enabled: true
  head: "xOSPREYx"
  title: "&b&lAvailable Servers"
  size: 27
  servers:
    13:
      name: Local
      ip: localhost
      port: 25565
      item:
        material: GRASS_BLOCK
        title: "&b&lElMedievo"
        lore:
          - ""
          - "hi"
chat:
  censored:
    enabled: false
    exempt-permission: "commons.censorship.bypass"
  vault-formatting:
    enabled: true
    format: "<{prefix}{name}&r{suffix}> {message}"
force-gamemode:
  enabled: true
  exempt-permission: "commons.defaultgamemode.exempt"
  gamemode: survival
joinquit-messages:
  enabled: false
  suppress: true
  join: "%prefix%&b%player%%suffix%&e joined the game"
  quit: "%prefix%&b%player%%suffix%&e left the game"
weather:
  disabled: true
lobby: "Lobby"
restart:
  enabled: true
  interval: 24h
tips:
  enabled: true
  interval: 7m
  prefix: "&7[&b&o&lTip&7] "
  messages:
    - "&7Visita nuestra web oficial: &bhttps://udecesports.com/"
    - "&7Síguenos en nuestro instagram &b@teamudecesports"
    - "&7¿Quieres ayudar al servidor? Adquiere un rango VIP en &bhttps://udecesports.buycraft.net/"
