name: Commons-PGM
version: ${project.version}
main: cl.bgmp.commonspgm.CommonsPGM
authors: [BGMP]
description: A legacy version of Unicraft Network's Commons plugin, which extends support for SportPaper
website: https://unicraft.cl/
depend: [PGM]
softdepend: [CommandBook]
